<a href="https://colab.research.google.com/github/Narmadakumbhkar/ASSISMENT_-QUESTION/blob/main/Numpy2_note_book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

# Arrays

In [ ]:
from numpy import *
# Single dimensional array 
array_data1 = [1.4, 7, 8, 12.3]
array1 = array(array_data1)
print("Array 1 : ",array1)

Array 1 :  [ 1.4  7.   8.  12.3]


In [ ]:
# Multi dimensional array 
#
array_data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2 = array(array_data2)
print("Array 2: ", array2)

Array 2:  [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Check the Dimension of the array 
print("Dimension of array2 is ",array2.ndim)

# Check the Size of Array 
print("Shape of array2 is ",array2.shape)

Dimension of array2 is  2
Shape of array2 is  (2, 4)


In [ ]:
# Create and array of zeros 
Zero_Array = zeros((3, 6))
print("Zero Array",Zero_Array)


Zero Array [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# Check Data Type of Array 
array_data1 = [1,2,3,4]
Array1 = array(array_data1)
print("data type of Array1 is : ",Array1.dtype)

data type of Array1 is :  int64


Arrays and Scalars
Notes:1) Operations between Arrays of same size happens element wise
Notes:2) Operations with Arrays and Scalars will propagate to each element

In [ ]:
#--------------------
# ELement wise array multiplication 
#--------------------
arr1 = array([[1,2,3],[4,5,6]])
arr2 = arr1*arr1 
print("Original Array ",arr1)
print("Element wise sq of arr1 is : ",arr2)
arr3 = arr1*2
print("Double array element wise", arr3)

Original Array  [[1 2 3]
 [4 5 6]]
Element wise sq of arr1 is :  [[ 1  4  9]
 [16 25 36]]
Double array element wise [[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#--------------------------------------------
# Indexing and slicing of arrays 
#--------------------------------------------
# Define Array of 10 elements 
Arr1 = array(arange(10))
print("Arr1 before manipulation is :",Arr1)


# Choose Index pos 3 to 5 and create a sub array 
# Note the 5th Index position actually does not get selected 
# Note: Only elemenst upto the 5th position get selected 
Sub_Arr1 = Arr1[3:5]
# Display elements of sub array 
print("Sub_Array before change is:",Sub_Arr1)
# Assign a fixed value to sub Array Index Pos 0 
Sub_Arr1[0] = 56
# Display elements of Sub_Arr1
print("Sub Array after change :",Sub_Arr1)



# Display elements of original array 
# Note: change in sub Array caused change in main array 
print("Original Array is",Arr1)



# Assign a element to the entire Sub array 
Sub_Arr1 = 66
# Display Sub Arry 
print("Sub Array after new assign is : ",Sub_Arr1)


# Display main Array 
print("Main Array after new assign is : ", Arr1)


Arr1 before manipulation is : [0 1 2 3 4 5 6 7 8 9]
Sub_Array before change is: [3 4]
Sub Array after change : [56  4]
Original Array is [ 0  1  2 56  4  5  6  7  8  9]
Sub Array after new assign is :  66
Main Array after new assign is :  [ 0  1  2 56  4  5  6  7  8  9]


In [ ]:
# Boolean Indexing 
#-------------------------------
# Create an Array of names 
Arr_Names = array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


# Get Array size
Arrsize = Arr_Names.shape
Len1 = Arrsize[0]


# Create a  Vector of random numbers of the same length
# Init a  Vector of size = Len1 
Rand_Set = array(arange(Len1))


# Populate Vector with Random nos from 1 to 10 
for i in range(Len1):
    Rand_Set[i-1] = random.uniform(1,10)
    
# Display Rand Vector
print("Rand Vector",Rand_Set)


# Get Those Index positions for which name = Bob 
# Use the index set to choose a sub set of Random Numbers 
Match_name_rand = Rand_Set[Arr_Names == 'Bob']
print("Matching Sub set of Rand Num is:",Match_name_rand)

Rand Vector [9 6 4 8 3 6 4]
Matching Sub set of Rand Num is: [9 8]


#Array Operations

In [ ]:
# Slicing multi dimensional Arrays 
# define a 3 by 4 array 
Array1 = array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array is ", Array1)
Array_Slice1 = Array1[2,:2]
print("Sliced Array is : ",Array_Slice1)

Original Array is  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array is :  [ 9 10]


In [ ]:
#-------------
# Square Root 
#-------------
from numpy import *
Arr = arange(10)
Sqrt_Arr = sqrt(Arr)
print("Sqrt Root values:", Sqrt_Arr )

Sqrt Root values: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [ ]:
#--------------------------
# Binary Function example 
#---------------------------

# Create Two Arrays of 10 random numbers each 
x = random.randn(10)
y = random.randn(10)
# Print  both the arrays 
print("X Array is :", x)
print("Y Array is :", y)
# Get the Element wise max, comparing both arrays 
Max_XY = maximum(x,y)
print("The Max element wise is :", Max_XY)

X Array is : [-0.06293734  1.57803025 -0.06620154  1.32639762 -0.23240541 -0.15965628
  0.73309881 -0.79761279  0.9004448   0.11336878]
Y Array is : [ 7.62347366e-01 -4.55654991e-04  9.15821011e-01  1.51415201e+00
 -5.06918789e-01 -2.47970134e+00  6.89197240e-01 -6.04774660e-01
  8.59858375e-01  4.91208897e-01]
The Max element wise is : [ 0.76234737  1.57803025  0.91582101  1.51415201 -0.23240541 -0.15965628
  0.73309881 -0.60477466  0.9004448   0.4912089 ]


In [ ]:
# Conditional logic as Array Operators
# ---
# Define Boolean Array 
Bool_Arr = array([True,False,True,False,True])
X_Arr = array([1,2,3,4,5])
Y_Arr = array([10,20,30,40,50])

Choice = [(X if Z else Y) for X,Y,Z in zip(X_Arr,Y_Arr,Bool_Arr)]
print("Choice: ",Choice)

Choice:  [1, 20, 3, 40, 5]


In [ ]:
#---------------------------------
# The where clause in arrays 
#---------------------------------
# Create a 3x3 array of random numbers 
Arr3 = random.randn(3,3)
print("original  Array is : ", Arr3)
# Replace pos numbers with +2 and _ve nos with -2 
Arr3_Chg = where(Arr3 > 0, 2, -2)
# Print changed Array 
print("Chg Array is : ", Arr3_Chg)

original  Array is :  [[-2.44872332  0.77068957 -0.6876222 ]
 [ 0.10548033 -0.26972485  0.92586402]
 [-0.16928784 -0.43330791 -0.44860913]]
Chg Array is :  [[-2  2 -2]
 [ 2 -2  2]
 [-2 -2 -2]]


#Basic Statistical functions


In [ ]:
Arr_Stat = array([[1,2,3],[4,5,6],[7,8,9]])
# Mean
Arr_Mean = mean(Arr_Stat) 
print("Mean of Array is: ",Arr_Mean)

Mean of Array is:  5.0


In [ ]:
# Sum 
Arr_Sum = sum(Arr_Stat)
print("Sum of Array is:",Arr_Sum)

Sum of Array is: 45


In [ ]:
# Get Column means (0th dimension or axis )
Arr_Mean_Cols = Arr_Stat.mean(0)
print("Col_Means = :", Arr_Mean_Cols)

Col_Means = : [4. 5. 6.]


#Misc Array operations

In [ ]:
#--------------------------------------------
#   Sorting 
#--------------------------------------------
Arr4 = array([10,2,34,5])
Arr4_Sorted = sorted(Arr4) 
print("Unsorted Array is ",Arr4)
print("Sorted Array is ",Arr4_Sorted)

Unsorted Array is  [10  2 34  5]
Sorted Array is  [2, 5, 10, 34]


In [ ]:
#-------------------------------------------------
#  Unique  and other Array set operations 
#-------------------------------------------------
# Create a Names Array 
Names_Arr = array(["Jim","Bob","Roy","Rajesh","Roy","Kumar","Jeet","Roy","Joy"])
# Get Unique Names 
Names_Arr_Unq = unique(Names_Arr)
print("Unique Names are ",Names_Arr_Unq)

Unique Names are  ['Bob' 'Jeet' 'Jim' 'Joy' 'Kumar' 'Rajesh' 'Roy']


In [ ]:
# Generate a 4 by 4  Array of random numbers following 
# Normal distribution 
#------------------------------------------------------
Arr4by4 = random.normal(size=(4,4))
print(Arr4by4)

[[-1.17443549 -0.44273671  0.49931428 -0.37992068]
 [ 1.48472689 -0.66741855 -0.75740058  0.94477976]
 [-0.50952087  1.41341462  0.67638494  0.72420833]
 [-0.24335429 -0.31215037 -0.52099013 -1.38097438]]


# END OF MODULE :- NUMPY